### ISSUE TITLE
Link is not working (404)

### ISSUE THREAD

**Issue by ghost** [mapkyca/KnownchatLogs#2]
The link in https://github.com/mapkyca/KnownchatLogs/blob/master/latest.md is not working, it produces a 404 Not Found

**Comment by mapkyca** [comment]
<a href="https://github.com/mapkyca/KnownchatLogs/issues/2" class="u-in-reply-to"></a>The script isn't smart enough to work out if there was any conversation that day before generating a latest.

People should talk more ;)
